name: Build Qt App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4

      - name: Set up MSVC
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '16.11'

      - name: Install Qt 5.15.2 (MSVC 2019)
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          install-deps: true
          setup-python: false

      - name: Build
        run: |
          cd src
          qmake edge-tts-gui.pro
          nmake release

      - name: Deploy
        run: |
          cd src/release
          windeployqt --no-translations --no-system-d3d-compiler --no-angle --no-opengl-sw edge-tts-gui.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: edge-tts-gui
          path: src/release/
