name: 编译C++为EXE
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 编译成EXE
        run: g++ communicate.cpp -o communicate.exe

      - name: 上传EXE文件
        uses: actions/upload-artifact@v4
        with:
          name: communicate程序
          path: communicate.exe
